/***********************************************************
*  Module       : JavaScript
*  Language     : Francais
*  Version      : 0.4
*  Created Date : 2008-01-15 21:36:13 Last change : 2008-03-27 13:34:21
*  Author       : ARIOS
*  License      : 

***********************************************************/


var alert_arr = {
		DELETE:"Voulez-vous supprimer la s\351lection ?",
		RECORDS:"Enregistrer ?",
		SELECT:"Merci de s\351lectionner au moins une entit\351",
		DELETE_ACCOUNT:"Supprimer ce(s) compte(s) va supprimer les affaires et devis li\351s. Etes-vous sûr de vouloir supprimer la s\351lection ?",
		DELETE_VENDOR:"Supprimer ce fournisseur va supprimer les commandes fournisseur li\351e. Etes vous sûr de vouloir supprimer l\'entr\351e s\351lectionn\351e ?",
		SELECT_MAILID:"Selectionnez un id de mail",
        OVERWRITE_EXISTING_ACCOUNT1:"Ecraser l\'adresse existante avec le compte s\351lectionn\351 (",
        OVERWRITE_EXISTING_ACCOUNT2:") d\351tails de l\'adresse ?",
		OVERWRITE_EXISTING_CONTACT1:"Ecraser l\'adresse existante avec le contact s\351lectionn\351 (",
        OVERWRITE_EXISTING_CONTACT2:") d\351tails de l\'adresse ?",
		MISSING_FIELDS:"Champs obligatoire manquant:",
		NOT_ALLOWED_TO_EDIT:"Vous n\'\352tes pas autoris\351 \340 modifier ce champs",
		NOT_ALLOWED_TO_EDIT_FIELDS:"Vous n\'\352tes pas autoris\351 \340 modifier ces champs",
		COLUMNS_CANNOT_BE_EMPTY:"Les colonnes s\351lectionn\351es ne peuvent \352tre vide",
		CANNOT_BE_EMPTY:"ne peut \352tre vide",
		CANNOT_BE_NONE:"ne peut-\352tre nulle",
		ENTER_VALID:"Merci d\'entrer correctement",
		SHOULDBE_LESS:"doit \352tre inf\351rieur \340",
		SHOULDBE_LESS_EQUAL:"doit \352tre inf\351rieur ou \351gal \340",
		SHOULDBE_EQUAL:"doit \352tre \351gal \340",
		SHOULDBE_GREATER:"doit \352tre sup\351rieur \340",
		SHOULDBE_GREATER_EQUAL:"doit \352tre sup\351rieur ou \351gal \340",
		INVALID:"Invalide",
		EXCEEDS_MAX:"D\351passe la limite maximale",
		OUT_OF_RANGE:"n\'est pas dans la norme",
		SHOULDNOTBE_EQUAL:"Ne peut pas \352tre \351gal \340",
		PORTAL_PROVIDE_EMAILID:"L\'utilisateur du portail client doit fournir un email pour se connecter",
		ADD_CONFIRMATION:"Etes vous sûr de vouloir ajouter la s\351lection",
		ACCOUNTNAME_CANNOT_EMPTY:"Le nom de compte doit \352tre renseign\351",
		CANT_SELECT_CONTACTS:"Vous ne pouvez pas s\351lectionner les contacts li\351s aux leads",
		LBL_THIS:"Ce",
		DOESNOT_HAVE_MAILIDS:"n\'a aucun id de mail",
		ARE_YOU_SURE:"\352tes vous sure ?",
		DOESNOT_HAVE_AN_MAILID:" n\'a aucun id de mail",
		MISSING_REQUIRED_FIELDS:"Champs requis manquants :",
		READONLY:"est en lecture seule",
		SELECT_ATLEAST_ONE_USER:"S\351lectionnez au moins un utilisateur",
		DISABLE_SHARING_CONFIRMATION:"\352tes-vous sûr d\'arr\352ter le partage avec la s\351lection",
		USERS:"Utilisateur(s) ?",
		ENDTIME_GREATER_THAN_STARTTIME:"La date de fin doit \352tre post\351rieure a celle de d\351but",
		FOLLOWUPTIME_GREATER_THAN_STARTTIME:"L\'heure de relance doit \352tre post\351rieure \340 l\'heure de fin",
		MISSING_EVENT_NAME:"Evenement inconnu",
		EVENT_TYPE_NOT_SELECTED:"Le type d\\\'activit\351 n\'est pas s\351lectionn\351",
		CLOSEDATE_CANNOT_BE_EMPTY:"La date de fin doit \352tre renseign\351e",
		SITEURL_CANNOT_BE_EMPTY:"L\'adresse du site doit \352tre renseign\351e",
		SITENAME_CANNOT_BE_EMPTY:"Le nom du site doit \352tre renseign\351",
		LISTPRICE_CANNOT_BE_EMPTY:"La grille tarifaire ne peut \352tre vide",
		INVALID_LIST_PRICE:"Grille tarifaire invalide",
		PROBLEM_ACCESSSING_URL:"Probl\350me d\'acc\350s \340 l\'adresse :",
		CODE:" Code : ",
		WISH_TO_QUALIFY_MAIL_AS_CONTACT:"\352tes-vous sûr de vouloir lier ce mail \340 ce contact ?",
		SELECT_ATLEAST_ONEMSG_TO_DEL:"S\351lectionnez au moins un message \340 supprimer",
		ERROR:"Erreur",
		FIELD_TYPE_NOT_SELECTED:"Le type de champs n\'est pas s\351lectionn\351",
		SPECIAL_CHARACTERS_NOT_ALLOWED:"Les caract\350res sp\351ciaux ne sont pas autoris\351s dans ce champs",
		SPECIAL_CHARACTERS:"Caract\350res sp\351ciaux",
		NOT_ALLOWED:"n\\\'est pas permis. Essayez de nouveau avec une nouvelle valeur",
		PICKLIST_CANNOT_BE_EMPTY:"La liste de choix ne peut \352tre vide",
		DUPLICATE_VALUES_FOUND:"Doublons d\351tect\351s",
		DUPLICATE_MAPPING_ACCOUNTS:"Duplicate mapping for accounts!!",
		DUPLICATE_MAPPING_CONTACTS:"Duplicate mapping for Contacts!!",
		DUPLICATE_MAPPING_POTENTIAL:"Duplicate mapping for Potential!!",
		ERROR_WHILE_EDITING:"Erreur d\'\351dition",
		CURRENCY_CHANGE_INFO:"Le changement de taux de change a \351t\351 effectu\351 avec succ\350s",
		CURRENCY_CONVERSION_INFO:"Are you using Dollar $ as Currency? \n Click OK to remain as $, Cancel to change the currency conversion rate.",
		THE_EMAILID:"L\'id de mail \\\'",
		EMAIL_FIELD_INVALID:"\\\' dans le mail est invalide",
		MISSING_REPORT_NAME:"Nom de rapport manquant",
		REPORT_NAME_EXISTS:"Nom de rapport d\351ja existant, essayez de nouveau...",
		WANT_TO_CHANGE_CONTACT_ADDR:"Souhaitez vous modifier l\'adresse du contact par l\'adresse du compte ?",
		SURE_TO_DELETE:"Etes vous sûr de vouloir supprimer ?",
		NO_PRODUCT_SELECTED:"Aucun produit s\351lectionn\351. S\351lectionnez-en au moins un",
		VALID_FINAL_PERCENT:"Entrez une remise en % valide",
		VALID_FINAL_AMOUNT:"Entrez un montant de remise valide",
		VALID_SHIPPING_CHARGE:"Entrez des frais de port valides",
		VALID_ADJUSTMENT:"Entrez un avoir/relicat valide",
		WANT_TO_CONTINUE:"Souhaitez-vous continuer ?",
		ENTER_VALID_TAX:"Entrez une valeur de taxe valide",
		VALID_TAX_NAME:"Entrez une taxe valide",
		CORRECT_TAX_VALUE:"Entrez un montant de taxe valide",
		ENTER_POSITIVE_VALUE:"Entrez une valeur positive",
		LABEL_SHOULDNOT_EMPTY:"Le nom de taxe doit \352tre renseign\351",
		NOT_VALID_ENTRY:"n\'est pas une entr\351e valide. Entrez une valeur correcte",
		VALID_DISCOUNT_PERCENT:"Entrez une remise en % valide",
		VALID_DISCOUNT_AMOUNT:"Entrez un montant de remise valide",
		SELECT_TEMPLATE_TO_MERGE:"S\351lectionnez le template \340 fusionner",
		SELECTED_MORE_THAN_ONCE:"Vous avez s\351lectionn\351 ce produit plus d\'une fois",
		YES:"oui",
		NO:"non",
		MAIL:"email",
		EQUALS:"\351gal",
		NOT_EQUALS_TO:"non \351gal \340",
		STARTS_WITH:"Commence avec",
		CONTAINS:"contient",
		DOES_NOT_CONTAINS:"ne contient pas",
		LESS_THAN:"inf\351rieur \340",
		GREATER_THAN:"sup\351rieur \340",
		LESS_OR_EQUALS:"inf\351rieur ou \351gal",
		GREATER_OR_EQUALS:"sup\351rieur ou \351gal \340",
		NO_SPECIAL_CHARS:"Les caract\350res sp\351ciaux ne sont pas autoris\351s dans les factures",
		PLS_SELECT_VALID_FILE:"Selectionnez un fichier avec cette extension:\n",
		NO_SPECIAL:"Les caract\350res sp\351ciaux ne sont pas autoris\351s",
		NO_QUOTES:"Les parenth\350ses et le symbole + ne sont pas autoris\351s",
		IN_PROFILENAME:"dans le profil",
		IN_GROUPNAME:"dans le groupe",
		IN_ROLENAME:"avec le rôle",
		VALID_TAX_PERCENT:"Entrez une taxe en % valide",
		VALID_SH_TAX:"Entrez une taxe sur les frais de ports valide",
		ROLE_DRAG_ERR_MSG:"Vous ne pouvez pas d\351placer un noeud parent dans un noeud enfant",
		LBL_DEL:"suppr",
		VALID_DATA:"Donn\351e invalide, r\351essayez svp",
		STDFILTER:"Filtes standards",
		STARTDATE:"Date de d\351but",
		ENDDATE:"Date de fin",
		START_DATE_TIME:"Date & heure de d\351but",
		START_TIME:"Heure de d\351but",
		DATE_SHOULDNOT_PAST:"Date & heure des activit\351s planifi\351es",
		TIME_SHOULDNOT_PAST:"Activit\351s courantes planifi\351es",
		LBL_AND:"Et",
		LBL_ENTER_VALID_PORT:"Entrez un num\351ro de port valide",
		IN_USERNAME:" dans le nom d\'utilisateur",
		LBL_ENTER_VALID_NO:"Entrez un nombre valide",
		LBL_PROVIDE_YES_NO:"Valeur incorrecte.\n R\351pondez par oui ou par non",
		LBL_SELECT_CRITERIA:"Crit\350re invalide.\n S\351lectionnez un autre crit\350re",
		OPPORTUNITYNAME_CANNOT_BE_EMPTY:"Le nom de l\'affaire doit \352tre renseign\351",
		OVERWRITE_EXISTING_ACCOUNT1:"Souhaitez-vous utiliser l\'adresse du compte en remplacement (",
		NAME_DESC:" pour le nom et la description du r\351pertoire",
		ENDS_WITH:"fini par",
		SHARED_EVENT_DEL_MSG:"L\'utilisateur n\'a pas l\'autorisation d\'\351diter/supprimer cette tâche",
		LBL_WRONG_IMAGE_TYPE:"Les extensions autoris\351es pour les contacts dont :- jpeg, png, jpg, pjpeg, x-png et gif",
		SELECT_MAIL_MOVE:"S\351lectionnez un email a d\351placer",
		LBL_NOTSEARCH_WITHSEARCH_ALL:"Vous n\'avez pas utilis\351 la recherche. Tous les enregistrement vont \352tre export\351s \340 partir de ",
		LBL_NOTSEARCH_WITHSEARCH_CURRENTPAGE:"You haven\'t searched any thing. But you selected with search & current page options. So the records in the current page will be Exported from ",
		LBL_NO_DATA_SELECTED:"Aucun enregistrement n\'est s\351lectionn\351. S\351lectionnez-en au moins un pour exporter",
		LBL_SEARCH_WITHOUTSEARCH_ALL:"Vous avez utilis\351 les options de recherche mais vous n\'avez pas s\351lectionn\351 d\'options.\nVous pouvez cliquer sur [ok] pour exporter toutes les donn\351es ou vous pouvez cliquer sur [annuler] et r\351essayer avec d\'autres param\350tres d\'export",
		STOCK_IS_NOT_ENOUGH:"Stock trop faible",
		INVALID_QTY:"Qt\351 invalide",
		LBL_SEARCH_WITHOUTSEARCH_CURRENTPAGE:"Vous avez utilis\351 les options de recherche mais vous n\'avez pas s\351lectionn\351 d\'options.\nVous pouvez cliquer sur [ok] pour exporter toutes les donn\351es ou vous pouvez cliquer sur [annuler] et r\351essayer avec d\'autres param\350tres d\'export",
		LBL_SELECT_COLUMN:"Colonne invalide. S\351lectionnez une autre colonne",
		LBL_NOT_ACCESSIBLE:"Non accessible",
		LBL_FILENAME_LENGTH_EXCEED_ERR:"Le nom de fichier ne peut d\351pacer 255 caract\350res",
		LBL_FILENAME_EMPTY_ERR:"Vous devez joindre obligatoirement un fichier",
		LBL_DONT_HAVE_EMAIL_PERMISSION:"Vous n\'avez pas la permission d\'\351diter le champs Email. Vous ne pouvez choisir l\'id de mail",
		LBL_NO_FEEDS_SELECTED:"Aucun flux s\351lectionn\351",
		LBL_SELECT_PICKLIST:"S\351lectionnez au moins une valeur a supprimer",
		LBL_CANT_REMOVE:"Vous ne pouvez supprimer toutes les valeurs",
		// rajout\351
		ALL_FILTER_CREATION_DENIED:"Vtiger ne peut pas cr\351er de vue personnalis\351e en utilisant le terme 'All', merci d\'essayer un autre nom pour cette vue",
		MSG_RESTORE_CONFIRMATION:"\352tes-vous sûr de vouloir restaurer la s\351lection",
		SAME_GROUPS: "Vous devez s\351lectionner les enregistrements dans le m\352me groupe pour les fusionner",
		ATLEAST_TWO: "S\351lectionner au moins deux enregistrements \340 fusionner",
		MAX_THREE: "Vous avez la possibilit\351 de s\351lectionner un maximum de 3 enregistrements",
		MAX_RECORDS: "Vous avez la possibilit\351 de s\351lectionner un maximum de 4 enregistrements",
		CON_MANDATORY: "S\351lectionnez le champ obligatoire 'Nom'",
		LE_MANDATORY: "S\351lectionnez les champs obligatoires 'Nom' et 'Soci\351t\351'",
		ACC_MANDATORY: "S\351lectionnez le champ obligatoire 'Compte'",
		PRO_MANDATORY: "S\351lectionnez le champ obligatoire 'Produit'",
		TIC_MANDATORY: "S\351lectionnez le champ obligatoire 'Titre du ticket'",
		POTEN_MANDATORY: "S\351lectionnez le champ obligatoire 'Nom de l\'Affaire'",
		VEN_MANDATORY: "S\351lectionnez le champ obligatoire 'Nom du Vendeur'",
		DEL_MANDATORY: "Vous n\'avez pas la possibilit\351 de supprimer le champ obligatoire",
		MSG_CHANGE_CURRENCY_REVISE_UNIT_PRICE: "Etes-vous sûr de vouloir mettre \340 jour les prix unitaires de chaque devise dans la devise s\351lectionn\351e ?",
		NO_SPECIAL_CHARS_DOCS:"Les caract\350res sp\351ciaux comme les guillemets, backslash, symboles math\351matiques, pourcentages et de ponctuation ne sont pas permis",
		OPERATION_DENIED:"Vous n\'avez pas les droits pour effectuer cette action",
		EMAIL_CHECK_MSG: "D\351sactiver l\'acc\350s au portail qui permet de conserver le champ email vide",
		IS_PARENT : "Ce produit est d\351clin\351 en sous-produits : vous n\'\352tes pas autoris\351 \340 choisir un 'parent' pour ce produit",
		
		AJOUTER_UTILISATEUR :"Voulez-vous ajouter les utilisateurs selectionnes ?",
		ACTIVER_UTILISATEUR :"Voulez-vous activer l'utilisateur selectionne ?",
		CONFIRMER_PRISE_EN_MAIN_DEMANDE :"Voulez-vous prendre en charge cette demande ?",
		CONFIRMER_PRISE_EN_MAIN_INCIDENT :"Voulez-vous prendre en charge cet incident ?",
		CONFIRMER_RELANCER_DEMANDE :"Voulez-vous relancer cette demande ?",
		CONFIRMER_RELANCER_INCIDENT :"Voulez-vous relancer cet incident ?",
		DATE_DERNIERE_RELANCE :"Date de derni\350re relance : ",
		CONFIRMER_RELANCER_DEMANDE_A_NOUVEAU :"Voulez-vous relancer \340 nouveau cette demande ?",
		CONFIRMER_RELANCER_INCIDENT_A_NOUVEAU :"Voulez-vous relancer \340 nouveau cet incident ?",
		INCIDENT_INVALIDE_TIME :"Veuillez renseigner l\'heure au format hh:mm ",
		INCIDENT_INCORRECT_TIME :"Veuillez renseigner une heure correcte au format hh:mm ",
		INCIDENT_INVALIDE_POPIMPACTEE :"Veuillez renseigner la population impact\351e !!! ",
		INCIDENT_INCORRECT_POPIMPACTEE :"Veuillez renseigner la population impact\351e au format entier !!! ",
		MOYENNE_INFERIEUR_14:"Votre moyenne doit \352tre sup\351rieur ou \351gal \340 14 pour pouvoir postuler",

		CONFIRMER_SOUMISSION_DEMANDE :"Voulez-vous soumettre cette demande \340 votre Commissaire?",
		CONFIRMER_SOUMISSION_DEMANDE_CJ :"Voulez-vous soumettre cette demande \340 votre Sup\351rieur?",
		CONFIRMER_SOUMISSION_DEMANDE_DCPC :"Voulez-vous soumettre cette demande au DC-PC?",
		
		CONFIRMER_SOUMISSION_HORSDELAI_DEMANDE :"Voulez-vous soumettre cette demande au DC/PC pour Hors Delai?",
		CONFIRMER_SOUMISSION_HORSBUDGET_DEMANDE :"Voulez-vous soumettre cette demande au DC/PC pour Hors Budget?",
		CONFIRMER_SAVEMODIFDECOMPTE_DEMANDE :"Voulez-vous enregistrer les modifications de cette decompte?",
		CONFIRMER_REMETTREENPREPA_DEMANDE :"Voulez-vous remettre cette demande en preparation?",
		CONFIRMER_REMETTREOMGENERE_DEMANDE :"Voulez-vous remettre cette demande \340 OM g\351n\351r\351?",
		CONFIRMER_ANNULER_DEMANDE :"Voulez-vous annuler cette demande?",
		CONFIRMER_REJETER_DEMANDE :"Voulez-vous rejeter cette demande?",
		CONFIRMER_ANNULER_MISSION :"Voulez-vous annuler cette mission?",
		CONFIRMER_ACCEPTER_DEMANDE :"Voulez-vous accepter cette demande?",
		CONFIRMER_MASS_VALIDER_DEMANDE :"Voulez-vous valider ce(s) ",
		CONFIRMER_MASS_Rejet_DEMANDE :"Voulez-vous rejeter ce(s) ",
		CONFIRMER_MASS_VALIDER2_DEMANDE :" demande(s)?",
		CONFIRMER_TOBECORRECTED_DEMANDE :"Voulez-vous renvoyer cette demande pour correction?",
		CONFIRMER_ANNULER_MISSION :"Voulez-vous annuler cette mission?",
		CONFIRMER_REMETTREASIGNE_DEMANDE :"Voulez-vous Mettre \340 sign\351 cette demande?",

		CONFIRMER_CREATION_ENGAGEMENT :"Voulez-vous creer l'engagement?",
		CONFIRMER_SOUMISSIONDC_DEMANDE :"Voulez-vous soumettre cette demande \340 votre Directeur de Cabinet?",
		
	
	};